name: CI
on:
  push:
    branches: [ ashkantaravati.github.io ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vue to Github Pages
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: ashkantaravati
          reponame: ashkantaravati.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          gitemail: ashkan.taravati@gmail.com
          gitname: ashkantaravati
          gitmsg: publish
          cname: ashkantaravati.ir
